name: Linter Check

on: [push]

jobs:
        runs-on: ubuntu-latest 
        steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
        run: |
          pip3 install poetry
          make install
        - name: Run linter
        run: make lint
